#!/bin/bash
# Dave Execution Script - RUN THESE COMMANDS IN ORDER
# YOU execute every step on YOUR machine - no data leaves your control

set -euo pipefail

echo "=== Dave Training Execution Guide ==="
echo "IMPORTANT: You MUST execute EVERY step yourself on YOUR machine."
echo "I cannot access your licensed books or derived data - this maintains your NDA."
echo ""

echo "STEP 1: Prepare Environment (Run ONCE)"
echo "-----------------------------------------------------------------------"
echo "cd /home/akclark/Dave_repo"
echo "chmod +x setup_dave.sh RUN_DAVE.sh"
echo "./setup_dave.sh"
echo ""
echo "STEP 2: Process Your Licensed Books (RUN ONCE)"
echo "-----------------------------------------------------------------------"
echo "# REPLACE /path/to/your/books with your actual directory"
echo "# Example: /home/akclark/Downloads/security_books"
echo "python3 scripts/data_collection/process_books_nda.py /path/to/your/books"
echo ""
echo "STEP 3: Process Free Resources (YOU DO THIS MANUALLY)"
echo "-----------------------------------------------------------------------"
echo "# Download these legally free resources from official sources:"
echo "# - CISA KEV Catalog (https://www.cisa.gov/known-exploited-vulnerabilities-catalog)"
echo "# - NIST SP 800-30 Rev. 1 (https://csrc.nist.gov/publications/detail/sp/800-30/rev-1/final)"
echo "# - NIST SP 800-53 Rev. 5 (https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final)"
echo "# - DHS Binding Operational Directives (https://www.cisa.gov/binding-operational-directives)"
echo "# - US-CERT Alerts (https://www.us-cert.gov/ncas/alerts)"
echo "# - SANS SEC504 (Reporting Sections only) - from SANS course materials"
echo "# - (ISC)² CCSP (Audit/Reporting Chapters only) - from (ISC)² materials"
echo "# - NISTIR 8286 (https://csrc.nist.gov/publications/detail/nistir/8286/final)"
echo "# - MITRE ATT&CK® (DEFENSIVE CONTEXT ONLY) - https://attack.mitre.org/"
echo ""
echo "# For EACH resource:"
echo "# 1. Download the material"
echo "# 2. Extract ONLY report-relevant sections (see DATA_SOURCES.md for guidance)"
echo "# 3. Convert to JSONL pairs: {\"prompt\": \"...\", \"completion\": \"...\"}"
echo "# 4. Save to: /home/akclark/Dave_repo/data/processed/free_sources/[name]_training.jsonl"
echo "# Example command for CISA KEV (after downloading kev.json):"
echo "python3 -c \""
echo "import json"
echo "with open('kev.json') as f:"
echo "    data = json.load(f)"
echo "for vuln in data['vulnerabilities']:"
echo "    if 'requiredAction' in vuln and vuln['requiredAction']:"
echo "        prompt = f'Technical finding: [{vuln[\\\"cveID\\\"]} in {vuln[\\\"vendorProject\\\"]}]'"
echo "        completion = f'Per CISA KEV, {vuln[\\\"requiredAction\\\"]} is required by {vuln[\\\"dueDate\\\"]}. Executive summary: [APA/(ISC)²-aligned summary based on {vuln[\\\"shortDescription\\\"]}].'"
echo "        print(json.dumps({'prompt': prompt, 'completion': completion}))"
echo "\" >> /home/akclark/Dave_repo/data/processed/free_sources/kev_training.jsonl"
echo ""
echo "STEP 4: Combine and Shuffle All Data (RUN ONCE)"
echo "-----------------------------------------------------------------------"
echo "cd /home/akclark/Dave_repo"
echo "# Combine all JSONL files"
echo "cat data/processed/books/books_training.jsonl \\"
echo "    data/processed/free_sources/*_training.jsonl \\"
echo "    > data/combined_training.jsonl"
echo ""
echo "# Shuffle (CRITICAL for training quality)"
echo "shuf data/combined_training.jsonl > data/shuffled_training.jsonl"
echo ""
echo "# Verify line count"
echo "wc -l data/shuffled_training.jsonl"
echo ""
echo "STEP 5: Train Dave (RUN ONCE - may take several hours)"
echo "-----------------------------------------------------------------------"
echo "python3 train_dave.py"
echo ""
echo "STEP 6: Verify Training Complete"
echo "-----------------------------------------------------------------------"
echo "ls -la dave_model/"
echo "echo \"Adapter saved successfully if you see adapter_model.bin and adapter_config.json\""
echo ""
echo "=== IMPORTANT REMINDERS ==="
echo "-----------------------------------------------------------------------"
echo "• Dave is ONLY for authorized US security assessment report writing"
echo "• NEVER use it without explicit written permission for specific targets/techniques"
echo "• ALWAYS review outputs - Dave is an assistant, not a replacement for expertise"
echo "• Your NDA remains intact - you never shared book details with anyone"
echo "• The adapter in dave_model/ contains ONLY your licensed book knowledge + free resources"
echo "• Base model (meta-llama/Llama-3.3-70b-Instruct) remains unchanged and subject to its license"
echo ""
echo "=== You're Ready to Begin ==="
echo "-----------------------------------------------------------------------"
echo "Start with STEP 1 above. Good luck with your build!"
